// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_auth_facebook = 'enable';
var aws_cloud_logic = 'enable';
var aws_cloud_logic_custom = [{"id":"xowkzms9a4","name":"pantry","description":"This API","endpoint":"https://xowkzms9a4.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}];
var aws_cognito_identity_pool_id = 'us-east-1:0fe5e82a-bf3f-466d-8c29-ec32f19b3f07';
var aws_cognito_region = 'us-east-1';
var aws_dynamodb = 'enable';
var aws_dynamodb_all_tables_region = 'us-east-1';
var aws_dynamodb_table_schemas = [{"tableName":"cloudpantry-mobilehub-37381707-pantryItems","attributes":[{"name":"userId","type":"S"},{"name":"pantryId","type":"S"},{"name":"expiryDate","type":"S"},{"name":"isLiquid","type":"BOOL"},{"name":"itemId","type":"S"},{"name":"name","type":"S"},{"name":"price","type":"N"},{"name":"quantity","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"pantryId"},{"tableName":"cloudpantry-mobilehub-37381707-pantries","attributes":[{"name":"userId","type":"S"},{"name":"id","type":"S"},{"name":"items","type":"L"},{"name":"name","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"id"}];
var aws_facebook_app_id = '378738719341266';
var aws_facebook_app_permissions = 'public_profile';
var aws_mandatory_sign_in = 'enable';
var aws_mobile_analytics_app_id = '08b8758deb3d41f4a2464da9451c2ccc';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '78667134-4e07-4629-b27c-8205abb006e5';
var aws_project_name = 'cloudpantry';
var aws_project_region = 'us-east-1';
var aws_resource_bucket_name = 'cloudpantry-deployments-mobilehub-37381707';
var aws_resource_name_prefix = 'cloudpantry-mobilehub-37381707';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-1_1MvgmQpAX';
var aws_user_pools_mfa_type = 'OFF';
var aws_user_pools_web_client_id = '6mnki6i1hrs1mq0gcv3pgei0qu';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
